import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case spanish = "es"
    case french = "fr"
    case german = "de"
    case catalan = "ca"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: L10n.string("language.english")
        case .spanish: L10n.string("language.spanish")
        case .french: L10n.string("language.french")
        case .german: L10n.string("language.german")
        case .catalan: L10n.string("language.catalan")
        }
    }

    var autonym: String {
        switch self {
        case .english: "English"
        case .spanish: "Español"
        case .french: "Français"
        case .german: "Deutsch"
        case .catalan: "Català"
        }
    }

    var locale: Locale {
        Locale(identifier: rawValue)
    }

    static func resolved(from rawValue: String?) -> AppLanguage {
        guard let rawValue else { return .english }
        if let exactMatch = AppLanguage(rawValue: rawValue) { return exactMatch }
        let normalized = rawValue.lowercased()
        if normalized.hasPrefix("es") { return .spanish }
        if normalized.hasPrefix("fr") { return .french }
        if normalized.hasPrefix("de") { return .german }
        if normalized.hasPrefix("ca") { return .catalan }
        return .english
    }
}

final class AppLanguageController: ObservableObject {
    @Published private(set) var currentLanguage: AppLanguage

    var locale: Locale {
        currentLanguage.locale
    }

    private let userDefaults: UserDefaults
    private let userDefaultsKey = "seriesav.appLanguage"

    init(userDefaults: UserDefaults = .standard) {
        self.userDefaults = userDefaults
        let storedLanguage = userDefaults.string(forKey: userDefaultsKey)
        let resolvedLanguage = AppLanguage.resolved(from: storedLanguage ?? Locale.preferredLanguages.first)
        currentLanguage = resolvedLanguage
        if storedLanguage == nil {
            userDefaults.set(resolvedLanguage.rawValue, forKey: userDefaultsKey)
        }
    }

    func select(_ language: AppLanguage) {
        guard currentLanguage != language else { return }
        currentLanguage = language
        userDefaults.set(language.rawValue, forKey: userDefaultsKey)
    }
}

enum L10n {
    static var locale: Locale {
        AppLanguage.resolved(from: UserDefaults.standard.string(forKey: "seriesav.appLanguage")).locale
    }

    static func string(_ key: String) -> String {
        translations[languageCode]?[key] ?? translations["en"]?[key] ?? key
    }

    static func string(_ key: String, _ arguments: CVarArg...) -> String {
        format(key, arguments: arguments)
    }

    static func markdown(_ key: String, _ arguments: CVarArg...) -> AttributedString {
        let localized = format(key, arguments: arguments)
        return (try? AttributedString(markdown: localized)) ?? AttributedString(localized)
    }

    static func plural(singular singularKey: String, plural pluralKey: String, count: Int, _ arguments: CVarArg...) -> String {
        format(count == 1 ? singularKey : pluralKey, arguments: arguments)
    }

    private static var languageCode: String {
        AppLanguage.resolved(from: UserDefaults.standard.string(forKey: "seriesav.appLanguage")).rawValue
    }

    private static func format(_ key: String, arguments: [CVarArg]) -> String {
        let format = string(key)
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: locale, arguments: arguments)
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "language.english": "English", "language.spanish": "Spanish", "language.french": "French", "language.german": "German", "language.catalan": "Catalan",
            "profile.statusTitle.account": "Account", "profile.title": "My profile", "profile.subtitle": "Tune the app, review your local library, and connect an account only when you need one.",
            "profile.displayName.local": "Local viewer", "profile.subtitle.guest": "No Account AV connected", "profile.subtitle.accountFallback": "Account AV",
            "profile.summary.account.title": "Session", "profile.summary.plan.title": "Access", "profile.summary.library.title": "Library",
            "profile.summary.account.detail.guest": "You are watching in local mode on this device.", "profile.summary.account.detail.signedIn": "Signed in", "profile.summary.plan.detail.guest": "Local mode", "profile.summary.plan.detail.free": "Connected account", "profile.summary.plan.detail.pro": "Pro",
            "profile.account.title": "Account", "profile.account.subtitle.guest": "Connect an Account AV to sync your series and social features.", "profile.account.subtitle.signedIn": "Manage the account used by Series AV.", "profile.account.status.title": "Status", "profile.account.status.guest": "Guest mode", "profile.account.status.signedIn": "Connected", "profile.account.email.title": "Email", "profile.account.connect": "Sign in", "profile.account.connectUnavailable": "Account sign-in unavailable in this build", "profile.account.identity.guest": "Local mode on this device", "profile.account.manage": "Manage account",
            "profile.plan.title": "Plan", "profile.plan.subtitle.guest": "Connect an account to see whether this profile is local, connected, or Pro.", "profile.plan.subtitle.free": "This first iOS release does not sell or manage subscriptions. Pro access is reflected here when it is enabled for your account.", "profile.plan.subtitle.unconfigured": "Pro purchases are not configured for this build.", "profile.plan.subtitle.pro": "Pro access is active for this account.", "profile.plan.sync.title": "Cloud sync", "profile.plan.sync.available": "Available with this account.", "profile.plan.sync.unavailable": "Requires Pro access.", "profile.plan.purchase": "Upgrade to Pro", "profile.plan.purchase.loading": "Opening purchase", "profile.plan.restore": "Restore purchases", "profile.plan.restore.loading": "Restoring purchases", "profile.plan.purchase.unavailable": "Purchases are not available in this build.", "profile.plan.purchase.completed": "Purchase recorded. Access will update after backend reconciliation.", "profile.plan.purchase.cancelled": "Purchase cancelled.", "profile.plan.purchase.pending": "Purchase pending Apple approval.", "profile.plan.active.title": "Pro active", "profile.plan.active.detail": "Premium features and cloud sync are enabled.", "profile.plan.release.title": "Subscriptions", "profile.plan.release.detail": "Subscription purchase and management are not available in iOS for this first release.",
            "profile.preferences.title": "App preferences", "profile.preferences.subtitle": "Pick how Series AV is shown on this device.", "profile.preferences.language.title": "App language", "profile.preferences.language.detail": "Choose the language used by the Series AV interface.", "profile.preferences.theme.title": "Appearance", "profile.preferences.theme.detail": "Choose whether Series AV follows the system appearance or always uses a fixed theme on this device.", "profile.preferences.theme.system": "System", "profile.preferences.theme.light": "Light", "profile.preferences.theme.dark": "Dark", "profile.preferences.accountPerk.title": "Connected account perk", "profile.preferences.accountPerk.detail": "Connect an account when you want to sync your series library and prepare premium features.", "profile.preferences.preferredGenre.title": "Preferred Home collection", "profile.preferences.preferredGenre.none": "No preferred collection", "profile.preferences.preferredGenre.detail": "Home opens around %@ while this account stays connected on this device.",
            "profile.social.title": "Account AV Social", "profile.social.subtitle": "Shared lists and recommendations powered by the Account AV backend.", "profile.social.recommendations": "Open recommendations", "profile.social.lists": "Open shared lists", "profile.social.createList": "Create shared list", "profile.social.refresh": "Refresh social data", "profile.social.unavailable.title": "Social features", "profile.social.unavailable.detail": "Sign in with Pro access to use recommendations and shared lists.",
            "profile.local.title": "On this device", "profile.local.subtitle": "Series, progress, and app settings remain on this device until backend-backed features exist.", "profile.local.series.count.one": "%d series", "profile.local.series.count.other": "%d series", "profile.local.favorites.count.one": "%d watching series on this device.", "profile.local.favorites.count.other": "%d watching series on this device.", "profile.local.recents.count.one": "%d series ready to continue on this device.", "profile.local.recents.count.other": "%d series ready to continue on this device.", "profile.local.savedMusic.title": "Completed series", "profile.local.savedMusic.count.one": "%d completed series on this device.", "profile.local.savedMusic.count.other": "%d completed series on this device.", "profile.local.limit.used": "%@ %d of %d used.", "profile.local.storagePolicy.title": "Storage policy", "profile.local.storagePolicy.local": "No backend access is used in this mode.", "profile.local.storagePolicy.remote": "Premium features can use backend-owned state.", "profile.actions.clearData": "Clear local data", "profile.actions.clearSyncedLibrary": "Clear synced library", "profile.actions.clearingData": "Clearing local data...", "profile.actions.clearingSyncedLibrary": "Clearing synced library...", "profile.actions.continue": "Continue with Apple or Google", "profile.actions.signOut": "Sign out", "profile.actions.signingOut": "Signing out...",
            "profile.help.title": "Help and legal", "profile.help.subtitle": "Open project links, support, privacy, and terms from here.", "profile.help.opensource.title": "Open-source project", "profile.help.opensource.detail": "Series AV is maintained as an independent open-source project.", "profile.help.sourceCode.title": "Source code", "profile.help.sourceCode.detail": "Browse the repository, issues, and contribution guidelines.", "profile.help.dataSources.title": "Data sources", "profile.help.dataSources.detail": "Series metadata is provided by TVMaze and configured backend providers.", "profile.help.support.title": "Contact support", "profile.help.support.detail": "Email Series AV support.", "profile.help.terms.title": "Terms of service", "profile.help.terms.detail": "Review the terms that apply to Series AV.", "profile.help.privacy.title": "Privacy policy", "profile.help.privacy.detail": "See how Series AV handles your data.",
            "profile.safety.title": "Account safety", "profile.safety.subtitle": "Sensitive account actions are handled in the account portal.", "profile.safety.delete.title": "Manage or delete account", "profile.safety.delete.detail": "Open the account portal to change details or delete the account.",
            "profile.sync.title": "Cloud sync", "profile.sync.subtitle": "Pro keeps your series library, progress, and settings ready across devices.", "profile.sync.status.title": "Cloud status", "profile.sync.status.idle": "Ready to sync when backend access is available.", "profile.sync.status.syncing": "Syncing library...", "profile.sync.status.synced": "Library is synced.", "profile.sync.status.conflict": "Cloud and this device both changed. Refresh from cloud before editing.", "profile.sync.status.failed": "Cloud sync could not complete. Try again when the backend is reachable.", "profile.sync.lastSynced.title": "Last synced", "profile.sync.retry": "Sync now", "profile.sync.retry.syncing": "Syncing...",
            "profile.alert.clearData.title": "Clear local data?", "profile.alert.clearData.cancel": "Cancel", "profile.alert.clearData.confirm": "Clear", "profile.alert.clearData.message": "Series, progress, and on-device settings will be removed from this device.", "profile.alert.clearSyncedLibrary.title": "Clear synced library?", "profile.alert.clearSyncedLibrary.message": "Your Series AV library, progress, and synced settings will be removed on all your devices. This does not affect your account.", "profile.alert.clearSyncedLibrary.confirm": "Clear synced library", "profile.alert.signOutFailed.title": "Couldn't sign out", "profile.alert.close": "Close", "shell.library.favorites.title": "Watching", "shell.home.recents.title": "Continue watching",
            "tab.home": "Home", "tab.library": "Library", "tab.discover": "Upcoming", "tab.profile": "Profile", "tab.search": "Search",
            "auth.feature.title": "Series, ready to follow.", "auth.feature.subtitle": "Track shows, save your progress, and get back to what you are watching without friction.", "auth.cta.localMode": "WATCH NOW", "auth.cta.subtitle.available": "You can watch without signing in.\nConnect an account later for sync and extra features.", "auth.cta.subtitle.unavailable": "Sign-in isn't configured in this build yet. You can still use Series AV locally on this device.", "auth.cta.continue": "SIGN IN", "auth.cta.skip": "SKIP FOR NOW", "auth.options.title": "Sign in", "auth.options.unavailable": "Sign-in is not configured in this build yet. Local mode is still available.", "auth.options.skip": "Skip for now", "auth.legalConsent": "By continuing, you agree to the [Terms](%1$@) and [Privacy Policy](%2$@) of Series AV.", "auth.alert.continueFailed.title": "Sign-in failed", "auth.alert.close": "Close"
            ,"shell.status.refreshing": "Refreshing", "shell.status.live": "Live", "state.loading.title": "Loading",
            "browse.popular": "Popular", "browse.comedy": "Comedy", "browse.drama": "Drama", "browse.scienceFiction": "Sci-Fi", "browse.animation": "Animation",
            "showStatus.watching": "Watching", "showStatus.completed": "Completed", "showStatus.paused": "Paused", "showStatus.dropped": "Dropped",
            "home.title": "Home", "home.subtitle": "Browse what to watch next, keep your favorites close, and pick up where you left off.", "home.continue.title": "Continue watching", "home.continue.subtitle": "Your active library stays front and center.", "home.featured.popular": "Popular picks", "home.featured.collection": "Featured %@", "home.featured.subtitle": "TVMaze-powered discovery with the Account AV visual system.", "home.error.title": "Browse unavailable", "home.error.detail": "Unable to load the browse feed right now.", "home.loading.detail": "Refreshing the current browse feed.", "home.now.eyebrow": "WHERE I AM NOW", "home.now.ready.status": "Ready", "home.now.watching.status": "Watching", "home.now.empty.title": "Ready for the first series", "home.now.empty.detail": "Add a series to your library and Series AV will keep this spot focused on the next episode.", "home.now.next": "Next: S%dE%d",
            "search.status.searching": "Searching", "search.title": "Search", "search.subtitle": "Find a series fast, then jump straight into seasons, progress, and your personal library.", "search.results.title": "Results for “%@”", "search.featured.title": "Featured %@", "search.results.subtitle": "Tap any result to inspect seasons, progress, and add it to your library.", "search.loading.inline": "Searching...", "search.loading.detail": "Refreshing results for the current request.", "search.error.title": "Search unavailable", "search.error.detail": "Search is unavailable right now.", "search.empty.title": "No results", "search.empty.detail": "Try another title or switch back to a browse collection.",
            "library.status.empty": "Empty", "library.status.saved": "%d Saved", "library.eyebrow": "Library", "library.title": "My Series", "library.subtitle": "Track what is active, done, paused, or dropped without turning the UI into clutter.", "library.search.prompt": "Search %@ shows", "library.empty.title": "No %@ series", "library.empty.detail": "This segment is empty right now.",
            "upcoming.title": "Upcoming", "upcoming.subtitle": "See what is ready next across the series you are following.", "upcoming.status.empty": "Empty", "upcoming.status.count": "%d next", "upcoming.status.ready": "Ready", "upcoming.spotlight.eyebrow": "NEXT UP", "upcoming.spotlight.fallback": "Open the series to review seasons, progress, and the next episode.", "upcoming.spotlight.empty.title": "Nothing queued yet", "upcoming.spotlight.empty.detail": "Add series to your library and keep them in Watching to build a next-up queue.", "upcoming.next.title": "Next episodes", "upcoming.next.subtitle": "Your active series sorted around what is coming next.", "upcoming.next.unknown": "Next episode pending", "upcoming.next.episode": "Next: S%dE%d", "upcoming.next.withDate": "Next: S%dE%d · %@", "upcoming.empty.title": "No upcoming series", "upcoming.empty.detail": "When you follow a series, its next episode will appear here.", "upcoming.queue.title": "On hold", "upcoming.queue.subtitle": "Paused and completed series you may want to revisit.", "upcoming.row.fallback": "Open the series to review progress and seasons.", "upcoming.row.ready": "READY"
            ,"splash.tagline": "Your series, ready to continue.", "splash.status": "Preparing Series AV"
        ],
        "es": [
            "language.english": "Inglés", "language.spanish": "Español", "language.french": "Francés", "language.german": "Alemán", "language.catalan": "Catalán",
            "profile.statusTitle.account": "Cuenta", "profile.title": "Mi perfil", "profile.subtitle": "Ajusta la app, revisa tu biblioteca local y conecta una cuenta solo si la necesitas.",
            "profile.displayName.local": "Espectador local", "profile.subtitle.guest": "Sin Account AV conectada", "profile.subtitle.accountFallback": "Account AV",
            "profile.summary.account.title": "Sesión", "profile.summary.plan.title": "Acceso", "profile.summary.library.title": "Biblioteca",
            "profile.summary.account.detail.guest": "Estás viendo en modo local en este dispositivo.", "profile.summary.account.detail.signedIn": "Sesión iniciada", "profile.summary.plan.detail.guest": "Modo local", "profile.summary.plan.detail.free": "Cuenta conectada", "profile.summary.plan.detail.pro": "Pro",
            "profile.account.title": "Cuenta", "profile.account.subtitle.guest": "Conecta una cuenta Account AV para sincronizar tus series y funciones sociales.", "profile.account.subtitle.signedIn": "Gestiona la cuenta usada por Series AV.", "profile.account.status.title": "Estado", "profile.account.status.guest": "Modo invitado", "profile.account.status.signedIn": "Conectada", "profile.account.email.title": "Email", "profile.account.connect": "Iniciar sesión", "profile.account.connectUnavailable": "El inicio de sesión no está disponible en esta build", "profile.account.identity.guest": "Modo local en este dispositivo", "profile.account.manage": "Gestionar cuenta",
            "profile.plan.title": "Plan", "profile.plan.subtitle.guest": "Conecta una cuenta para ver si este perfil es local, conectado o Pro.", "profile.plan.subtitle.free": "La primera release en iOS no vende ni gestiona suscripciones. El acceso Pro se reflejará aquí cuando esté activo en tu cuenta.", "profile.plan.subtitle.unconfigured": "Las compras Pro no están configuradas en esta build.", "profile.plan.subtitle.pro": "El acceso Pro está activo para esta cuenta.", "profile.plan.sync.title": "Sincronización cloud", "profile.plan.sync.available": "Disponible con esta cuenta.", "profile.plan.sync.unavailable": "Requiere acceso Pro.", "profile.plan.purchase": "Actualizar a Pro", "profile.plan.purchase.loading": "Abriendo compra", "profile.plan.restore": "Restaurar compras", "profile.plan.restore.loading": "Restaurando compras", "profile.plan.purchase.unavailable": "Las compras no están disponibles en esta build.", "profile.plan.purchase.completed": "Compra registrada. El acceso se actualizará tras la reconciliación backend.", "profile.plan.purchase.cancelled": "Compra cancelada.", "profile.plan.purchase.pending": "Compra pendiente de aprobación de Apple.", "profile.plan.active.title": "Pro activo", "profile.plan.active.detail": "Funciones premium y sincronización cloud activadas.", "profile.plan.release.title": "Suscripciones", "profile.plan.release.detail": "La compra y la gestión de suscripciones no están disponibles en iOS en esta primera release.",
            "profile.preferences.title": "Preferencias de la app", "profile.preferences.subtitle": "Elige como se muestra Series AV en este dispositivo.", "profile.preferences.language.title": "Idioma de la app", "profile.preferences.language.detail": "Elige el idioma que usa la interfaz de Series AV.", "profile.preferences.theme.title": "Apariencia", "profile.preferences.theme.detail": "Elige si Series AV sigue la apariencia del sistema o usa siempre un tema fijo en este dispositivo.", "profile.preferences.theme.system": "Sistema", "profile.preferences.theme.light": "Claro", "profile.preferences.theme.dark": "Oscuro", "profile.preferences.accountPerk.title": "Ventaja de cuenta conectada", "profile.preferences.accountPerk.detail": "Conecta una cuenta cuando quieras sincronizar tu biblioteca de series y preparar funciones premium.", "profile.preferences.preferredGenre.title": "Colección preferida de Inicio", "profile.preferences.preferredGenre.none": "Sin colección preferida", "profile.preferences.preferredGenre.detail": "Inicio se abrirá alrededor de %@ mientras esta cuenta siga conectada en este dispositivo.",
            "profile.social.title": "Account AV Social", "profile.social.subtitle": "Listas compartidas y recomendaciones del backend de Account AV.", "profile.social.recommendations": "Abrir recomendaciones", "profile.social.lists": "Abrir listas compartidas", "profile.social.createList": "Crear lista compartida", "profile.social.refresh": "Actualizar datos sociales", "profile.social.unavailable.title": "Funciones sociales", "profile.social.unavailable.detail": "Inicia sesión con acceso Pro para usar recomendaciones y listas compartidas.",
            "profile.local.title": "En este dispositivo", "profile.local.subtitle": "Series, progreso y ajustes permanecen en este dispositivo hasta que existan funciones con backend.", "profile.local.series.count.one": "%d serie", "profile.local.series.count.other": "%d series", "profile.local.favorites.count.one": "%d serie en seguimiento en este dispositivo.", "profile.local.favorites.count.other": "%d series en seguimiento en este dispositivo.", "profile.local.recents.count.one": "%d serie lista para continuar en este dispositivo.", "profile.local.recents.count.other": "%d series listas para continuar en este dispositivo.", "profile.local.savedMusic.title": "Series completadas", "profile.local.savedMusic.count.one": "%d serie completada en este dispositivo.", "profile.local.savedMusic.count.other": "%d series completadas en este dispositivo.", "profile.local.limit.used": "%@ %d de %d usados.", "profile.local.storagePolicy.title": "Política de almacenamiento", "profile.local.storagePolicy.local": "No se usa acceso backend en este modo.", "profile.local.storagePolicy.remote": "Las funciones premium pueden usar estado gestionado por backend.", "profile.actions.clearData": "Borrar datos locales", "profile.actions.clearSyncedLibrary": "Borrar biblioteca sincronizada", "profile.actions.clearingData": "Borrando datos locales...", "profile.actions.clearingSyncedLibrary": "Borrando biblioteca sincronizada...", "profile.actions.continue": "Continuar con Apple o Google", "profile.actions.signOut": "Cerrar sesión", "profile.actions.signingOut": "Cerrando sesión...",
            "profile.help.title": "Ayuda y legal", "profile.help.subtitle": "Abre enlaces del proyecto, soporte, privacidad y términos desde aquí.", "profile.help.opensource.title": "Proyecto open-source", "profile.help.opensource.detail": "Series AV se mantiene como un proyecto open-source e independiente.", "profile.help.sourceCode.title": "Código fuente", "profile.help.sourceCode.detail": "Consulta el repositorio, issues y guías de contribución.", "profile.help.dataSources.title": "Fuentes de datos", "profile.help.dataSources.detail": "Los metadatos de series vienen de TVMaze y proveedores backend configurados.", "profile.help.support.title": "Contactar soporte", "profile.help.support.detail": "Escribe al soporte de Series AV.", "profile.help.terms.title": "Términos de servicio", "profile.help.terms.detail": "Revisa los términos aplicables a Series AV.", "profile.help.privacy.title": "Política de privacidad", "profile.help.privacy.detail": "Consulta cómo Series AV gestiona tus datos.",
            "profile.safety.title": "Seguridad de cuenta", "profile.safety.subtitle": "Las acciones sensibles se gestionan desde el portal de cuenta.", "profile.safety.delete.title": "Gestionar o eliminar cuenta", "profile.safety.delete.detail": "Abre el portal de cuenta para cambiar datos o eliminar la cuenta.",
            "profile.sync.title": "Sincronización en la nube", "profile.sync.subtitle": "Pro mantiene tu biblioteca de series, progreso y ajustes listos entre dispositivos.", "profile.sync.status.title": "Estado de la nube", "profile.sync.status.idle": "Lista para sincronizar cuando el backend esté disponible.", "profile.sync.status.syncing": "Sincronizando biblioteca...", "profile.sync.status.synced": "La biblioteca está sincronizada.", "profile.sync.status.conflict": "La nube y este dispositivo han cambiado. Actualiza desde la nube antes de editar.", "profile.sync.status.failed": "La sincronización no se ha podido completar. Inténtalo de nuevo cuando el backend esté disponible.", "profile.sync.lastSynced.title": "Última sincronización", "profile.sync.retry": "Sincronizar ahora", "profile.sync.retry.syncing": "Sincronizando...",
            "profile.alert.clearData.title": "¿Borrar datos locales?", "profile.alert.clearData.cancel": "Cancelar", "profile.alert.clearData.confirm": "Borrar", "profile.alert.clearData.message": "Series, progreso y ajustes del dispositivo se eliminarán de este dispositivo.", "profile.alert.clearSyncedLibrary.title": "¿Borrar biblioteca sincronizada?", "profile.alert.clearSyncedLibrary.message": "Se eliminarán tu biblioteca, progreso y ajustes sincronizados de Series AV en todos tus dispositivos. No afecta a tu cuenta.", "profile.alert.clearSyncedLibrary.confirm": "Borrar biblioteca sincronizada", "profile.alert.signOutFailed.title": "No se pudo cerrar sesión", "profile.alert.close": "Cerrar", "shell.library.favorites.title": "En seguimiento", "shell.home.recents.title": "Continuar viendo",
            "tab.home": "Inicio", "tab.library": "Biblioteca", "tab.discover": "Próximos", "tab.profile": "Perfil", "tab.search": "Buscar",
            "auth.feature.title": "Series listas para seguir.", "auth.feature.subtitle": "Controla tus series, guarda el progreso y vuelve a lo que estabas viendo sin fricción.", "auth.cta.localMode": "VER AHORA", "auth.cta.subtitle.available": "Puedes ver series sin iniciar sesión.\nConecta una cuenta más adelante para sincronizar y usar funciones extra.", "auth.cta.subtitle.unavailable": "El inicio de sesión aún no está configurado en esta compilación. Puedes seguir usando Series AV de forma local en este dispositivo.", "auth.cta.continue": "INICIAR SESIÓN", "auth.cta.skip": "OMITIR POR AHORA", "auth.options.title": "Iniciar sesión", "auth.options.unavailable": "El inicio de sesión aún no está configurado en esta compilación. El modo local sigue disponible.", "auth.options.skip": "Omitir por ahora", "auth.legalConsent": "Al continuar, aceptas los [Términos](%1$@) y la [Política de privacidad](%2$@) de Series AV.", "auth.alert.continueFailed.title": "No se pudo iniciar sesión", "auth.alert.close": "Cerrar"
            ,"shell.status.refreshing": "Actualizando", "shell.status.live": "En vivo", "state.loading.title": "Cargando",
            "browse.popular": "Popular", "browse.comedy": "Comedia", "browse.drama": "Drama", "browse.scienceFiction": "Sci-Fi", "browse.animation": "Animación",
            "showStatus.watching": "En seguimiento", "showStatus.completed": "Completadas", "showStatus.paused": "Pausadas", "showStatus.dropped": "Descartadas",
            "home.title": "Inicio", "home.subtitle": "Explora qué ver después, mantén tus favoritas cerca y retoma donde lo dejaste.", "home.continue.title": "Continuar viendo", "home.continue.subtitle": "Tu biblioteca activa siempre queda a mano.", "home.featured.popular": "Populares", "home.featured.collection": "%@ destacadas", "home.featured.subtitle": "Descubrimiento con TVMaze y el sistema visual de Account AV.", "home.error.title": "Exploración no disponible", "home.error.detail": "No se pudo cargar la selección ahora mismo.", "home.loading.detail": "Actualizando la selección actual.", "home.now.eyebrow": "DÓNDE ESTOY", "home.now.ready.status": "Listo", "home.now.watching.status": "Viendo", "home.now.empty.title": "Lista para la primera serie", "home.now.empty.detail": "Añade una serie a tu biblioteca y Series AV mantendrá este espacio centrado en el siguiente episodio.", "home.now.next": "Siguiente: T%dE%d",
            "search.status.searching": "Buscando", "search.title": "Buscar", "search.subtitle": "Encuentra una serie rápido y salta a temporadas, progreso y biblioteca personal.", "search.results.title": "Resultados para “%@”", "search.featured.title": "%@ destacadas", "search.results.subtitle": "Toca cualquier resultado para revisar temporadas, progreso y añadirlo a tu biblioteca.", "search.loading.inline": "Buscando...", "search.loading.detail": "Actualizando resultados para la búsqueda actual.", "search.error.title": "Búsqueda no disponible", "search.error.detail": "La búsqueda no está disponible ahora mismo.", "search.empty.title": "Sin resultados", "search.empty.detail": "Prueba otro título o vuelve a una colección.", 
            "library.status.empty": "Vacía", "library.status.saved": "%d guardadas", "library.eyebrow": "Biblioteca", "library.title": "Mis series", "library.subtitle": "Controla qué está activo, terminado, pausado o descartado sin añadir ruido.", "library.search.prompt": "Buscar series %@", "library.empty.title": "Sin series %@", "library.empty.detail": "Este segmento está vacío ahora mismo.",
            "upcoming.title": "Próximos", "upcoming.subtitle": "Mira qué toca después en las series que sigues.", "upcoming.status.empty": "Vacía", "upcoming.status.count": "%d próximas", "upcoming.status.ready": "Listo", "upcoming.spotlight.eyebrow": "SIGUIENTE", "upcoming.spotlight.fallback": "Abre la serie para revisar temporadas, progreso y el siguiente episodio.", "upcoming.spotlight.empty.title": "Nada en cola todavía", "upcoming.spotlight.empty.detail": "Añade series a tu biblioteca y mantenlas en seguimiento para crear una cola.", "upcoming.next.title": "Siguientes episodios", "upcoming.next.subtitle": "Tus series activas ordenadas por lo que viene después.", "upcoming.next.unknown": "Siguiente episodio pendiente", "upcoming.next.episode": "Siguiente: T%dE%d", "upcoming.next.withDate": "Siguiente: T%dE%d · %@", "upcoming.empty.title": "Sin próximas series", "upcoming.empty.detail": "Cuando sigas una serie, su siguiente episodio aparecerá aquí.", "upcoming.queue.title": "En espera", "upcoming.queue.subtitle": "Series pausadas y completadas que quizá quieras retomar.", "upcoming.row.fallback": "Abre la serie para revisar progreso y temporadas.", "upcoming.row.ready": "LISTO"
            ,"splash.tagline": "Tus series, listas para continuar.", "splash.status": "Preparando Series AV"
        ],
        "ca": [
            "language.english": "Anglès", "language.spanish": "Espanyol", "language.french": "Francès", "language.german": "Alemany", "language.catalan": "Català",
            "profile.statusTitle.account": "Compte", "profile.title": "Perfil", "profile.subtitle": "Gestiona el compte, l'aparença, les dades del dispositiu i les funcions socials d'Account AV.",
            "profile.displayName.local": "Espectador convidat", "profile.subtitle.guest": "Aquesta versió funciona primer en local i permet iniciar sessió opcionalment.", "profile.subtitle.accountFallback": "Sessió iniciada a Account AV.",
            "profile.summary.account.title": "Compte", "profile.summary.plan.title": "Pla", "profile.summary.library.title": "Biblioteca",
            "profile.summary.account.detail.guest": "Navegant localment com a convidat.", "profile.summary.account.detail.signedIn": "Sessió iniciada com a %@.", "profile.summary.plan.detail.guest": "Accés convidat", "profile.summary.plan.detail.free": "Accés gratuït", "profile.summary.plan.detail.pro": "Accés Pro",
            "profile.account.title": "Compte", "profile.account.subtitle.guest": "Connecta un compte Account AV per sincronitzar les sèries i funcions socials.", "profile.account.subtitle.signedIn": "Gestiona el compte usat per Series AV.", "profile.account.status.title": "Estat", "profile.account.status.guest": "Mode convidat", "profile.account.status.signedIn": "Connectat", "profile.account.email.title": "Email", "profile.account.connect": "Connectar compte", "profile.account.connectUnavailable": "L'inici de sessio no esta disponible en aquesta build", "profile.account.identity.guest": "Mode local en aquest dispositiu", "profile.account.manage": "Gestionar compte",
            "profile.plan.title": "Pla", "profile.plan.subtitle.guest": "Connecta un compte per veure si aquest perfil és local, connectat o Pro.", "profile.plan.subtitle.free": "La primera release a iOS no ven ni gestiona subscripcions. L'accés Pro es reflectirà aquí quan estigui actiu al teu compte.", "profile.plan.subtitle.unconfigured": "Les compres Pro no estan configurades en aquesta build.", "profile.plan.subtitle.pro": "L'accés Pro està actiu per a aquest compte.", "profile.plan.sync.title": "Sincronització cloud", "profile.plan.sync.available": "Disponible amb aquest compte.", "profile.plan.sync.unavailable": "Requereix accés Pro.", "profile.plan.purchase": "Actualitzar a Pro", "profile.plan.purchase.loading": "Obrint compra", "profile.plan.restore": "Restaurar compres", "profile.plan.restore.loading": "Restaurant compres", "profile.plan.purchase.unavailable": "Les compres no estan disponibles en aquesta build.", "profile.plan.purchase.completed": "Compra registrada. L'accés s'actualitzarà després de la reconciliació backend.", "profile.plan.purchase.cancelled": "Compra cancel·lada.", "profile.plan.purchase.pending": "Compra pendent d'aprovació d'Apple.", "profile.plan.active.title": "Pro actiu", "profile.plan.active.detail": "Funcions premium i sincronització cloud activades.", "profile.plan.release.title": "Subscripcions", "profile.plan.release.detail": "La compra i la gestió de subscripcions no estan disponibles a iOS en aquesta primera release.",
            "profile.preferences.title": "Preferències", "profile.preferences.subtitle": "Tria l'idioma i l'aparença utilitzats en aquest dispositiu.", "profile.preferences.language.title": "Idioma", "profile.preferences.language.detail": "Tria l'idioma de l'app.", "profile.preferences.theme.title": "Tema", "profile.preferences.theme.detail": "Sistema, clar o fosc.", "profile.preferences.theme.system": "Sistema", "profile.preferences.theme.light": "Clar", "profile.preferences.theme.dark": "Fosc",
            "profile.social.title": "Account AV Social", "profile.social.subtitle": "Llistes compartides i recomanacions del backend d'Account AV.", "profile.social.recommendations": "Obrir recomanacions", "profile.social.lists": "Obrir llistes compartides", "profile.social.createList": "Crear llista compartida", "profile.social.refresh": "Actualitzar dades socials", "profile.social.unavailable.title": "Funcions socials", "profile.social.unavailable.detail": "Inicia sessió amb accés Pro per usar recomanacions i llistes compartides.",
            "profile.local.title": "Dades locals", "profile.local.subtitle": "Sèries desades en aquest dispositiu i sincronitzades quan sigui possible.", "profile.local.series.count.one": "%d sèrie", "profile.local.series.count.other": "%d sèries", "profile.local.storagePolicy.title": "Política d'emmagatzematge", "profile.local.storagePolicy.local": "Només local en aquest dispositiu.", "profile.local.storagePolicy.remote": "Sincronització al núvol disponible.", "profile.actions.clearData": "Esborrar dades locals", "profile.actions.clearingData": "Esborrant dades", "profile.actions.continue": "Continuar amb Apple o Google", "profile.actions.signOut": "Tancar sessió", "profile.actions.signingOut": "Tancant sessió",
            "profile.help.title": "Ajuda i legal", "profile.help.subtitle": "Suport, termes, privacitat i fonts de dades.", "profile.help.opensource.title": "Codi obert", "profile.help.opensource.detail": "Series AV manté el mateix shell d'Account AV i client Swift natiu.", "profile.help.dataSources.title": "Fonts de dades", "profile.help.dataSources.detail": "Les metadades de sèries venen de TVMaze i proveïdors backend configurats.", "profile.help.support.title": "Suport", "profile.help.support.detail": "Contacta amb suport d'Account AV.", "profile.help.terms.title": "Termes", "profile.help.terms.detail": "Llegeix els termes d'Series AV.", "profile.help.privacy.title": "Privacitat", "profile.help.privacy.detail": "Llegeix la política de privacitat d'Series AV.",
            "profile.safety.title": "Seguretat del compte", "profile.safety.subtitle": "Gestiona accions sensibles des de la pàgina de compte d'Account AV.", "profile.safety.delete.title": "Eliminar compte", "profile.safety.delete.detail": "Obre la gestió de compte per revisar opcions d'eliminació.",
            "profile.alert.clearData.title": "Esborrar dades locals?", "profile.alert.clearData.cancel": "Cancel·lar", "profile.alert.clearData.confirm": "Esborrar", "profile.alert.clearData.message": "Això elimina la biblioteca local d'Series AV i restableix els ajustos en aquest dispositiu.", "profile.alert.close": "Tancar"
        ],
        "fr": [
            "language.english": "Anglais", "language.spanish": "Espagnol", "language.french": "Français", "language.german": "Allemand", "language.catalan": "Catalan",
            "profile.statusTitle.account": "Compte", "profile.title": "Profil", "profile.subtitle": "Gérez le compte, l'apparence, les données de l'appareil et les fonctions sociales d'Account AV.",
            "profile.displayName.local": "Spectateur invité", "profile.subtitle.guest": "Cette version fonctionne d'abord en local et la connexion reste facultative.", "profile.subtitle.accountFallback": "Connecté à Account AV.",
            "profile.summary.account.title": "Compte", "profile.summary.plan.title": "Offre", "profile.summary.library.title": "Bibliothèque",
            "profile.summary.account.detail.guest": "Navigation locale en tant qu'invité.", "profile.summary.account.detail.signedIn": "Connecté en tant que %@.", "profile.summary.plan.detail.guest": "Accès invité", "profile.summary.plan.detail.free": "Accès gratuit", "profile.summary.plan.detail.pro": "Accès Pro",
            "profile.account.title": "Compte", "profile.account.subtitle.guest": "Connectez un compte Account AV pour synchroniser vos séries et les fonctions sociales.", "profile.account.subtitle.signedIn": "Gérez le compte utilisé par Series AV.", "profile.account.status.title": "État", "profile.account.status.guest": "Mode invité", "profile.account.status.signedIn": "Connecté", "profile.account.email.title": "E-mail", "profile.account.connect": "Connecter le compte", "profile.account.connectUnavailable": "La connexion n'est pas disponible dans cette build", "profile.account.identity.guest": "Mode local sur cet appareil", "profile.account.manage": "Gérer le compte",
            "profile.plan.title": "Offre", "profile.plan.subtitle.guest": "Connectez un compte pour voir si ce profil est local, connecté ou Pro.", "profile.plan.subtitle.free": "Cette première release iOS ne vend pas et ne gère pas les abonnements. L'accès Pro apparaîtra ici lorsqu'il sera actif sur votre compte.", "profile.plan.subtitle.unconfigured": "Les achats Pro ne sont pas configurés dans cette build.", "profile.plan.subtitle.pro": "L'accès Pro est actif pour ce compte.", "profile.plan.sync.title": "Synchronisation cloud", "profile.plan.sync.available": "Disponible avec ce compte.", "profile.plan.sync.unavailable": "Nécessite l'accès Pro.", "profile.plan.purchase": "Passer à Pro", "profile.plan.purchase.loading": "Ouverture de l'achat", "profile.plan.restore": "Restaurer les achats", "profile.plan.restore.loading": "Restauration des achats", "profile.plan.purchase.unavailable": "Les achats ne sont pas disponibles dans cette build.", "profile.plan.purchase.completed": "Achat enregistré. L'accès sera mis à jour après réconciliation backend.", "profile.plan.purchase.cancelled": "Achat annulé.", "profile.plan.purchase.pending": "Achat en attente d'approbation Apple.", "profile.plan.active.title": "Pro actif", "profile.plan.active.detail": "Fonctions premium et synchronisation cloud activées.", "profile.plan.release.title": "Abonnements", "profile.plan.release.detail": "L'achat et la gestion des abonnements ne sont pas disponibles sur iOS pour cette première release.",
            "profile.preferences.title": "Préférences", "profile.preferences.subtitle": "Choisissez la langue et l'apparence utilisées sur cet appareil.", "profile.preferences.language.title": "Langue", "profile.preferences.language.detail": "Choisissez la langue de l'app.", "profile.preferences.theme.title": "Thème", "profile.preferences.theme.detail": "Système, clair ou sombre.", "profile.preferences.theme.system": "Système", "profile.preferences.theme.light": "Clair", "profile.preferences.theme.dark": "Sombre",
            "profile.social.title": "Account AV Social", "profile.social.subtitle": "Listes partagées et recommandations du backend Account AV.", "profile.social.recommendations": "Ouvrir les recommandations", "profile.social.lists": "Ouvrir les listes partagées", "profile.social.createList": "Créer une liste partagée", "profile.social.refresh": "Actualiser les données sociales", "profile.social.unavailable.title": "Fonctions sociales", "profile.social.unavailable.detail": "Connectez-vous avec un accès Pro pour utiliser recommandations et listes partagées.",
            "profile.local.title": "Données locales", "profile.local.subtitle": "Séries stockées sur cet appareil et synchronisées si possible.", "profile.local.series.count.one": "%d série", "profile.local.series.count.other": "%d séries", "profile.local.storagePolicy.title": "Politique de stockage", "profile.local.storagePolicy.local": "Local uniquement sur cet appareil.", "profile.local.storagePolicy.remote": "Synchronisation cloud disponible.", "profile.actions.clearData": "Effacer les données locales", "profile.actions.clearingData": "Effacement des données", "profile.actions.continue": "Continuer avec Apple ou Google", "profile.actions.signOut": "Se déconnecter", "profile.actions.signingOut": "Déconnexion",
            "profile.help.title": "Aide et légal", "profile.help.subtitle": "Support, conditions, confidentialité et sources de données.", "profile.help.opensource.title": "Open source", "profile.help.opensource.detail": "Series AV conserve le même shell Account AV et le client Swift natif.", "profile.help.dataSources.title": "Sources de données", "profile.help.dataSources.detail": "Les métadonnées des séries proviennent de TVMaze et des fournisseurs backend configurés.", "profile.help.support.title": "Support", "profile.help.support.detail": "Contacter le support Account AV.", "profile.help.terms.title": "Conditions", "profile.help.terms.detail": "Lire les conditions d'Series AV.", "profile.help.privacy.title": "Confidentialité", "profile.help.privacy.detail": "Lire la politique de confidentialité d'Series AV.",
            "profile.safety.title": "Sécurité du compte", "profile.safety.subtitle": "Gérez les actions sensibles depuis la page du compte Account AV.", "profile.safety.delete.title": "Supprimer le compte", "profile.safety.delete.detail": "Ouvrir la gestion du compte pour voir les options de suppression.",
            "profile.alert.clearData.title": "Effacer les données locales ?", "profile.alert.clearData.cancel": "Annuler", "profile.alert.clearData.confirm": "Effacer", "profile.alert.clearData.message": "Cela supprime votre bibliothèque locale Series AV et réinitialise les réglages de cet appareil.", "profile.alert.close": "Fermer"
        ],
        "de": [
            "language.english": "Englisch", "language.spanish": "Spanisch", "language.french": "Französisch", "language.german": "Deutsch", "language.catalan": "Katalanisch",
            "profile.statusTitle.account": "Konto", "profile.title": "Profil", "profile.subtitle": "Konto, Darstellung, Gerätedaten und soziale Account AV-Funktionen verwalten.",
            "profile.displayName.local": "Gastzuschauer", "profile.subtitle.guest": "Verbinde Account AV, um zu synchronisieren und soziale Funktionen zu nutzen.", "profile.subtitle.accountFallback": "Bei Account AV angemeldet.",
            "profile.summary.account.title": "Konto", "profile.summary.plan.title": "Plan", "profile.summary.library.title": "Bibliothek",
            "profile.summary.account.detail.guest": "Lokales Browsen als Gast.", "profile.summary.account.detail.signedIn": "Angemeldet als %@.", "profile.summary.plan.detail.guest": "Gastzugang", "profile.summary.plan.detail.free": "Kostenloser Zugang", "profile.summary.plan.detail.pro": "Pro-Zugang",
            "profile.account.title": "Konto", "profile.account.subtitle.guest": "Verbinde ein Account AV-Konto, um Serien und soziale Funktionen zu synchronisieren.", "profile.account.subtitle.signedIn": "Verwalte das von Series AV genutzte Konto.", "profile.account.status.title": "Status", "profile.account.status.guest": "Gastmodus", "profile.account.status.signedIn": "Verbunden", "profile.account.email.title": "E-Mail", "profile.account.connect": "Konto verbinden", "profile.account.connectUnavailable": "Kontoanmeldung ist in diesem Build nicht verfügbar", "profile.account.identity.guest": "Lokaler Modus auf diesem Gerät", "profile.account.manage": "Konto verwalten",
            "profile.plan.title": "Plan", "profile.plan.subtitle.guest": "Verbinde ein Konto, um zu sehen, ob dieses Profil lokal, verbunden oder Pro ist.", "profile.plan.subtitle.free": "Diese erste iOS-Release verkauft oder verwaltet keine Abos. Pro-Zugang wird hier angezeigt, wenn er für dein Konto aktiv ist.", "profile.plan.subtitle.unconfigured": "Pro-Käufe sind in diesem Build nicht konfiguriert.", "profile.plan.subtitle.pro": "Pro-Zugang ist für dieses Konto aktiv.", "profile.plan.sync.title": "Cloud-Sync", "profile.plan.sync.available": "Für dieses Konto verfügbar.", "profile.plan.sync.unavailable": "Erfordert Pro-Zugang.", "profile.plan.purchase": "Auf Pro upgraden", "profile.plan.purchase.loading": "Kauf wird geöffnet", "profile.plan.restore": "Käufe wiederherstellen", "profile.plan.restore.loading": "Käufe werden wiederhergestellt", "profile.plan.purchase.unavailable": "Käufe sind in diesem Build nicht verfügbar.", "profile.plan.purchase.completed": "Kauf erfasst. Zugang wird nach Backend-Abgleich aktualisiert.", "profile.plan.purchase.cancelled": "Kauf abgebrochen.", "profile.plan.purchase.pending": "Kauf wartet auf Apple-Freigabe.", "profile.plan.active.title": "Pro aktiv", "profile.plan.active.detail": "Premium-Funktionen und Cloud-Sync sind aktiviert.", "profile.plan.release.title": "Abonnements", "profile.plan.release.detail": "Kauf und Verwaltung von Abonnements sind in iOS für diese erste Release nicht verfügbar.",
            "profile.preferences.title": "Einstellungen", "profile.preferences.subtitle": "Wähle Sprache und Darstellung für dieses Gerät.", "profile.preferences.language.title": "Sprache", "profile.preferences.language.detail": "App-Sprache auswählen.", "profile.preferences.theme.title": "Design", "profile.preferences.theme.detail": "System, hell oder dunkel.", "profile.preferences.theme.system": "System", "profile.preferences.theme.light": "Hell", "profile.preferences.theme.dark": "Dunkel",
            "profile.social.title": "Account AV Social", "profile.social.subtitle": "Geteilte Listen und Empfehlungen aus dem Account AV-Backend.", "profile.social.recommendations": "Empfehlungen öffnen", "profile.social.lists": "Geteilte Listen öffnen", "profile.social.createList": "Geteilte Liste erstellen", "profile.social.refresh": "Soziale Daten aktualisieren", "profile.social.unavailable.title": "Soziale Funktionen", "profile.social.unavailable.detail": "Melde dich mit Pro-Zugang an, um Empfehlungen und geteilte Listen zu nutzen.",
            "profile.local.title": "Lokale Daten", "profile.local.subtitle": "Auf diesem Gerät gespeicherte Serien, synchronisiert wenn verfügbar.", "profile.local.series.count.one": "%d Serie", "profile.local.series.count.other": "%d Serien", "profile.local.storagePolicy.title": "Speicherregel", "profile.local.storagePolicy.local": "Nur lokal auf diesem Gerät.", "profile.local.storagePolicy.remote": "Cloud-Sync verfügbar.", "profile.actions.clearData": "Lokale Daten löschen", "profile.actions.clearingData": "Daten werden gelöscht", "profile.actions.continue": "Mit Apple oder Google fortfahren", "profile.actions.signOut": "Abmelden", "profile.actions.signingOut": "Abmeldung",
            "profile.help.title": "Hilfe und Rechtliches", "profile.help.subtitle": "Support, Bedingungen, Datenschutz und Datenquellen.", "profile.help.opensource.title": "Open Source", "profile.help.opensource.detail": "Series AV nutzt dieselbe Account AV-Shell und den nativen Swift-Client.", "profile.help.dataSources.title": "Datenquellen", "profile.help.dataSources.detail": "Serienmetadaten kommen von TVMaze und konfigurierten Backend-Anbietern.", "profile.help.support.title": "Support", "profile.help.support.detail": "Account AV-Support kontaktieren.", "profile.help.terms.title": "Bedingungen", "profile.help.terms.detail": "Series AV-Bedingungen lesen.", "profile.help.privacy.title": "Datenschutz", "profile.help.privacy.detail": "Series AV-Datenschutzrichtlinie lesen.",
            "profile.safety.title": "Kontosicherheit", "profile.safety.subtitle": "Sensible Kontoaktionen über die Account AV-Kontoseite verwalten.", "profile.safety.delete.title": "Konto löschen", "profile.safety.delete.detail": "Kontoverwaltung öffnen, um Löschoptionen zu prüfen.",
            "profile.alert.clearData.title": "Lokale Daten löschen?", "profile.alert.clearData.cancel": "Abbrechen", "profile.alert.clearData.confirm": "Löschen", "profile.alert.clearData.message": "Dies entfernt deine lokale Series AV-Bibliothek und setzt die Einstellungen auf diesem Gerät zurück.", "profile.alert.close": "Schließen"
        ]
    ]
}
